services:
    web:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
        ports:
            - "8000:8000"
        env_file:
          - ./.env
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
    static_volume: