version: "3.9"

services:
    web:
        build: .
        container_name: django
        command: gunicorn personal_assistant_web.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - pgdb
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    celery:
        build: .
        command: celery -A personal_assistant_web worker -l INFO
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        depends_on:
            - web
            - redis
    redis:
        image: "redis:alpine"
    celery-beat:
        build: .
        command: celery -A personal_assistant_web beat -l info --pidfile=/tmp/celeryd.pid
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        depends_on:
            - redis
    nginx:
        build: ./nginx
        volumes:
            - ./staticfiles:/home/app/web/staticfiles:ro
        ports:
            - 80:80
        depends_on:
            - web
volumes:
    pgdata:
    static_volume:
